# Generated by Django 4.0.1 on 2022-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('duration', models.FloatField()),
                ('size', models.FloatField()),
                ('singer', models.CharField(max_length=77)),
            ],
        ),
    ]
