# Generated by Django 4.0.1 on 2022-03-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('name', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hero')),
            ],
        ),
    ]
