# Generated by Django 4.0.1 on 2022-03-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroin',
            fields=[
                ('hname', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('hero', models.ManyToManyField(to='app.Hero')),
            ],
        ),
    ]
