# Generated by Django 4.0.1 on 2022-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_hero_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='role',
            field=models.IntegerField(blank=True, db_column='role in movie', null=True),
        ),
    ]
