# Generated by Django 4.0.1 on 2022-03-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
