# Generated by Django 4.0.1 on 2022-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('hy', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
