# Generated by Django 4.0.1 on 2022-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_temp_hy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('hlo', models.AutoField(db_column='auto-field', primary_key=True, serialize=False)),
            ],
        ),
    ]
