# Generated by Django 4.0.1 on 2022-03-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
