# Generated by Django 4.0.1 on 2022-03-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slugo',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
